"""empty message

Revision ID: 231c055159d5
Revises: 1d9bbb3120e9
Create Date: 2026-06-29 18:34:18.716825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231c055159d5'
down_revision: Union[str, Sequence[str], None] = '1d9bbb3120e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'cover_photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('cover_photo_url', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
